#!/usr/bin/env python3
"""Collect the licence text of every crate linked into the WebAssembly blob.

`docs/licensing.md` says it plainly: MIT, BSD and Apache-2.0 all require the
copyright notice and licence text to travel with binaries, and "shipping
without it is the one way a permissive licence can still be breached." The npm
package is a binary distribution — one .wasm with about a hundred crates
statically linked into it — and until 0.2.0 it shipped readany's own LICENSE
and nothing else. `NOTICES` at the repository root covers only PDFium, which
this crate does not link at all.

So this is the missing half: the notice for everything that is actually in the
blob. Written out to THIRD-PARTY-LICENSES.md and shipped in the package.

Proc-macro crates are excluded deliberately. They run at build time and emit
code; none of their own object code is linked into the artefact, so they are
not distributed and their notices do not need to travel.

    ./scripts/third-party-licenses.py > THIRD-PARTY-LICENSES.md
"""

import hashlib
import os
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CARGO_HOME = Path(os.environ.get("CARGO_HOME", Path.home() / ".cargo"))
REGISTRY = CARGO_HOME / "registry" / "src"

LICENCE_FILENAMES = re.compile(
    r"^(licen[cs]e|copying|notice|unlicense)([-_.].*)?$", re.IGNORECASE
)


def linked_crates():
    """Every crate whose object code ends up in the blob."""
    out = subprocess.run(
        [
            "cargo", "tree",
            "--target", "wasm32-unknown-unknown",
            "-e", "normal",
            "--prefix", "none",
            "--format", "{p}|{l}|{r}",
        ],
        cwd=REPO / "wasm",
        capture_output=True,
        text=True,
        check=True,
    ).stdout

    seen = {}
    for line in out.splitlines():
        line = line.strip().removesuffix(" (*)")
        if not line or "|" not in line:
            continue
        spec, licence, repo = (line.split("|", 2) + ["", ""])[:3]
        # Build-time only: emits code, contributes none of its own.
        if "(proc-macro)" in spec:
            continue
        # Path dependencies are this project.
        if "(/" in spec:
            continue
        parts = spec.split()
        if len(parts) < 2:
            continue
        name, version = parts[0], parts[1].lstrip("v")
        seen[(name, version)] = (licence.strip(), repo.strip())
    return dict(sorted(seen.items()))


def licence_texts(name, version):
    """The crate's own licence files, as (filename, text) pairs."""
    found = []
    for registry in REGISTRY.glob("*"):
        directory = registry / f"{name}-{version}"
        if not directory.is_dir():
            continue
        for path in sorted(directory.iterdir()):
            if path.is_file() and LICENCE_FILENAMES.match(path.name):
                try:
                    text = path.read_text(encoding="utf-8", errors="replace").strip()
                except OSError:
                    continue
                if text:
                    found.append((path.name, text))
        break
    return found


def main():
    crates = linked_crates()
    missing = []

    # Identical texts are stored once and referenced. Apache-2.0 is about
    # 11 KB and appears in roughly eighty of these crates; written out per
    # crate the file is a megabyte, almost all of it the same page repeated.
    # Deduplicating changes nothing about the obligation — the notice still
    # travels, in full — and it makes the file something a person could
    # actually read.
    #
    # MIT texts do *not* deduplicate, and must not: they differ by the
    # copyright line, which names the holder, and that line is the part MIT
    # actually requires to travel.
    bodies = {}
    order = []
    per_crate = {}

    for (name, version), (spdx, repo) in crates.items():
        texts = licence_texts(name, version)
        if not texts:
            missing.append(f"{name} {version}")
        refs = []
        for filename, text in texts:
            # A digest rather than `hash()`: Python randomises string hashing
            # per process, and a generated file that differs run to run is a
            # generated file nobody can review in a diff.
            key = hashlib.sha256(text.encode("utf-8")).hexdigest()
            if key not in bodies:
                bodies[key] = (len(order) + 1, filename, text)
                order.append(key)
            refs.append((bodies[key][0], filename))
        per_crate[(name, version)] = refs

    print("# Third-party licences")
    print()
    print("Every crate whose code is linked into `readany_wasm_bg.wasm`, with the")
    print("licence text its authors ship. Generated by")
    print("`scripts/third-party-licenses.py`; do not edit by hand.")
    print()
    print("Proc-macro crates are not listed: they run at build time and none of")
    print("their object code is distributed.")
    print()
    print(f"{len(crates)} crates, {len(order)} distinct licence texts.")
    print()
    print("## The crates")
    print()
    print("| Crate | Version | SPDX | Licence text |")
    print("|---|---|---|---|")
    for (name, version), (spdx, repo) in crates.items():
        refs = per_crate[(name, version)]
        if refs:
            cited = ", ".join(f"[L{n}](#l{n}-{f.lower().replace('.', '').replace('_', '-')})"
                              for n, f in refs)
        else:
            cited = "none published"
        link = f"[{name}]({repo})" if repo else name
        print(f"| {link} | {version} | `{spdx or 'not declared'}` | {cited} |")
    print()

    print("## The licence texts")
    print()
    for key in order:
        number, filename, text = bodies[key]
        anchor = filename.lower().replace(".", "").replace("_", "-")
        print(f"### L{number} {anchor}")
        print()
        print("```")
        print(text)
        print("```")
        print()

    if missing:
        print(
            f"\nNote: {len(missing)} crate(s) publish no licence file in their "
            "source: " + ", ".join(missing) + ".",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
